name: Deploy Q-Learning App

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Smoke test imports
        run: |
          python - <<'PY'
          import importlib
          for m in ("tic_tac_toe_env","q_learning_agent","training_system"):
              importlib.import_module(m)
          print("✅ imports OK")
          PY

 deploy-railway:
  needs: test
  runs-on: ubuntu-latest
  if: github.ref == 'refs/heads/main'
  steps:
    - uses: actions/checkout@v4

    - name: Set up Node (for Railway CLI)
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Install Railway CLI
      run: npm i -g @railway/cli

    - name: Login + Link project + Deploy
      env:
        RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        RAILWAY_PROJECT_ID: ${{ secrets.RAILWAY_PROJECT_ID }}
      run: |
        railway login --token "$RAILWAY_TOKEN"
        railway link --project "$RAILWAY_PROJECT_ID"
        # If you have multiple services, set the exact service name:
        railway up --service "q-learning-tictactoe" --ci --detach
        # (Optionally: add --environment "production" if you use multiple envs)

  deploy-render:
    needs: test
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Deploy to Render
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.RENDER_SERVICE_ID }}
          api-key: ${{ secrets.RENDER_API_KEY }}
